Error: failed external call: __ubsan_handle_out_of_bounds
File: testing/oob2/segments/segment_2_klee.c
Line: 27
assembly.ll line: 8099
State: 24
Stack: 
	#000008099 in update_employee(138976153305088, symbolic) at testing/oob2/segments/segment_2_klee.c:27
	#100008212 in __klee_posix_wrapped_main() at testing/oob2/segments/segment_2_klee.c:41
	#200006090 in __user_main(1, 140191092178944, 140191092178960) at src/runtime/POSIX/klee_init_env.c:245
	#300000544 in __uClibc_main(140175313207296, 1, 140191092178944, 0, 0, 0, 0) at libc/misc/internals/__uClibc_main.c:401
	#400000709 in main(1, 140191092178944)
